//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFuel.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevFuel.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an external item to the view. Use AddNew() or add to source list instead..
        /// </summary>
        internal static string BLV_CannotAddItem {
            get {
                return ResourceManager.GetString("BLV_CannotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new item due to no object being provided in the AddingNew event and a lack of default public constructor..
        /// </summary>
        internal static string BLV_CannotAddNewItem {
            get {
                return ResourceManager.GetString("BLV_CannotAddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new item when NewItemsList is null..
        /// </summary>
        internal static string BLV_CannotAddWhenNewItemsListNull {
            get {
                return ResourceManager.GetString("BLV_CannotAddWhenNewItemsListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clear this view..
        /// </summary>
        internal static string BLV_CannotClearView {
            get {
                return ResourceManager.GetString("BLV_CannotClearView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert an external item into this collection..
        /// </summary>
        internal static string BLV_CannotInsertItem {
            get {
                return ResourceManager.GetString("BLV_CannotInsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set an item in the view..
        /// </summary>
        internal static string BLV_CannotSetItem {
            get {
                return ResourceManager.GetString("BLV_CannotSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includeDelegate cannot be null..
        /// </summary>
        internal static string BLV_IncludeDelegateCannotBeNull {
            get {
                return ResourceManager.GetString("BLV_IncludeDelegateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item in list is not of type {0}..
        /// </summary>
        internal static string BLV_InvalidListItemType {
            get {
                return ResourceManager.GetString("BLV_InvalidListItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list does not implement IList..
        /// </summary>
        internal static string BLV_InvalidSourceList {
            get {
                return ResourceManager.GetString("BLV_InvalidSourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was not of type {0}..
        /// </summary>
        internal static string BLV_ItemTypeIncorrect {
            get {
                return ResourceManager.GetString("BLV_ItemTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no filter).
        /// </summary>
        internal static string BLV_NoFilter {
            get {
                return ResourceManager.GetString("BLV_NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null..
        /// </summary>
        internal static string BLV_ObjectCannotBeNull {
            get {
                return ResourceManager.GetString("BLV_ObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (predicate filter).
        /// </summary>
        internal static string BLV_PredicateFilter {
            get {
                return ResourceManager.GetString("BLV_PredicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} does not exist in type {1}..
        /// </summary>
        internal static string BLV_PropertyNotFound {
            get {
                return ResourceManager.GetString("BLV_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list already added to the view..
        /// </summary>
        internal static string BLV_SourceListAlreadyAdded {
            get {
                return ResourceManager.GetString("BLV_SourceListAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list is not in the view..
        /// </summary>
        internal static string BLV_SourceListNotFound {
            get {
                return ResourceManager.GetString("BLV_SourceListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLists cannot be null..
        /// </summary>
        internal static string BLV_SourceListsNull {
            get {
                return ResourceManager.GetString("BLV_SourceListsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized access to the view is not supported..
        /// </summary>
        internal static string BLV_SyncAccessNotSupported {
            get {
                return ResourceManager.GetString("BLV_SyncAccessNotSupported", resourceCulture);
            }
        }
    }
}
